pipeline {
   agent any
   stages{
      stage('checkout') {
         steps {
            checkout scm
         }
      }
       stage('Login docker') {
          steps {
            sh 'docker login -u $USERNAME -p $PASSWORD'
          }
       }

       stage('Docker build and push') {
          steps {
             sh 'docker build -t $USERNAME/chat-app-api:$BUILD_NUMBER .'
             sh 'docker push $USERNAME/chat-app-api:$BUILD_NUMBER'
             sh 'docker run -dp 4090:4090 $USERNAME/chat-app-api:$BUILD_NUMBER'
             sh 'docker logout'
          }
       }
       // Testing
        stage('Testing') {
            steps{
                dir('DevopsChatApp') {
                    script {
                        sh 'curl 127.0.0.1:4090'
                        echo 'Testing... be continued...'
                    }
                }
            }
        }
   }
}
